"""Initial migration

Revision ID: 7ebf6963643c
Revises: 
Create Date: 2025-08-24 20:54:01.712290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebf6963643c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='boom_blog'
    )
    op.create_index(op.f('ix_boom_blog_users_email'), 'users', ['email'], unique=True, schema='boom_blog')
    op.create_index(op.f('ix_boom_blog_users_id'), 'users', ['id'], unique=False, schema='boom_blog')
    op.create_index(op.f('ix_boom_blog_users_username'), 'users', ['username'], unique=True, schema='boom_blog')
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['boom_blog.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='boom_blog'
    )
    op.create_index(op.f('ix_boom_blog_posts_id'), 'posts', ['id'], unique=False, schema='boom_blog')
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['boom_blog.posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['boom_blog.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='boom_blog'
    )
    op.create_index(op.f('ix_boom_blog_comments_id'), 'comments', ['id'], unique=False, schema='boom_blog')
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['boom_blog.posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['boom_blog.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id'),
    schema='boom_blog'
    )
    op.create_table('views',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['boom_blog.posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['boom_blog.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id'),
    schema='boom_blog'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('views', schema='boom_blog')
    op.drop_table('likes', schema='boom_blog')
    op.drop_index(op.f('ix_boom_blog_comments_id'), table_name='comments', schema='boom_blog')
    op.drop_table('comments', schema='boom_blog')
    op.drop_index(op.f('ix_boom_blog_posts_id'), table_name='posts', schema='boom_blog')
    op.drop_table('posts', schema='boom_blog')
    op.drop_index(op.f('ix_boom_blog_users_username'), table_name='users', schema='boom_blog')
    op.drop_index(op.f('ix_boom_blog_users_id'), table_name='users', schema='boom_blog')
    op.drop_index(op.f('ix_boom_blog_users_email'), table_name='users', schema='boom_blog')
    op.drop_table('users', schema='boom_blog')
    # ### end Alembic commands ###
