"""Add like_count and view_count to posts

Revision ID: e183281baa8d
Revises: 7ebf6963643c
Create Date: 2025-08-25 08:30:58.806631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e183281baa8d'
down_revision: Union[str, None] = '7ebf6963643c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], source_schema='boom_blog', referent_schema='boom_blog')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], source_schema='boom_blog', referent_schema='boom_blog')
    op.drop_constraint('likes_post_id_fkey', 'likes', type_='foreignkey')
    op.drop_constraint('likes_user_id_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'], source_schema='boom_blog', referent_schema='boom_blog')
    op.create_foreign_key(None, 'likes', 'posts', ['post_id'], ['id'], source_schema='boom_blog', referent_schema='boom_blog')
    op.add_column('posts', sa.Column('like_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('view_count', sa.Integer(), nullable=True))
    op.drop_constraint('posts_author_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'], source_schema='boom_blog', referent_schema='boom_blog')
    op.drop_constraint('views_user_id_fkey', 'views', type_='foreignkey')
    op.drop_constraint('views_post_id_fkey', 'views', type_='foreignkey')
    op.create_foreign_key(None, 'views', 'posts', ['post_id'], ['id'], source_schema='boom_blog', referent_schema='boom_blog')
    op.create_foreign_key(None, 'views', 'users', ['user_id'], ['id'], source_schema='boom_blog', referent_schema='boom_blog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'views', schema='boom_blog', type_='foreignkey')
    op.drop_constraint(None, 'views', schema='boom_blog', type_='foreignkey')
    op.create_foreign_key('views_post_id_fkey', 'views', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('views_user_id_fkey', 'views', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'posts', schema='boom_blog', type_='foreignkey')
    op.create_foreign_key('posts_author_id_fkey', 'posts', 'users', ['author_id'], ['id'])
    op.drop_column('posts', 'view_count')
    op.drop_column('posts', 'like_count')
    op.drop_constraint(None, 'likes', schema='boom_blog', type_='foreignkey')
    op.drop_constraint(None, 'likes', schema='boom_blog', type_='foreignkey')
    op.create_foreign_key('likes_user_id_fkey', 'likes', 'users', ['user_id'], ['id'])
    op.create_foreign_key('likes_post_id_fkey', 'likes', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'comments', schema='boom_blog', type_='foreignkey')
    op.drop_constraint(None, 'comments', schema='boom_blog', type_='foreignkey')
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
